### ISSUE TITLE
jazz install on linux mint error 

### ISSUE THREAD

**Issue by nodrygo** [jazzscheme/jazz#6]
hello trying to install Jazz on my Linux mint I got 

**error file not fount** **_io.c_**

following Gambit doc install instructions I have change in the **jaz** : 
_gambit_make ()_
with:
```
gambit_make () {
    ( [ -f "$GAMBITSOURCE/config.status" ] || gambit_configure ) &&
    cd "$GAMBITSOURCE" &&
    make -j8 current-gsc-boot &&
    make -j8 from-scratch
    # make $(jobs) from-scratch
}
```
and now it work fine

hope this can help

**Comment by jazzscheme** [comment]
Fixed by commit 0da56008774645b6f2352c229cb62130700fecf8
Update gambit_make (thanks to nodrygo)
