### ISSUE TITLE
error jaz make on linux mint 

### ISSUE THREAD

**Issue by nodrygo** [jazzscheme/jazz#7]
may be this is a misuse from me ? 
jaz make

```
*** WARNING -- "##jazzstruct?" is not defined,
***            referenced in: ("bin/build/kernel/runtime/record.cpp")
; linking executable...
*** ERROR IN link-image, "kernel/runtime/build.scm"@870.15 -- Wrong number of arguments passed to procedure
(##gambcomp
 'C
 'exe
 "/home/ygo/devygo/jazz/jazz/bin/"
 '("bin/build/kernel/syntax/verbose.o" "bin/build/kernel/_architecture.o" "bin/build/products/kernel/_product.o" "bin/build/kernel/syntax/heade...
 "/home/ygo/devygo/jazz/jazz/bin//jazz"
 #f
 #f
 '(("CC_OPTIONS" . "-I/home/ygo/devygo/jazz/jazz/foreign/gambit/include") ("LD_OPTIONS_PRELUDE" . "") ("LD_OPTIONS" . "-L/home/ygo/devygo/jazz/...
)
*** ERROR IN jazz:make-product, "kernel/build.scm"@1442.3 -- Process failed (17920): (path: "sh" arguments: ("/home/ygo/devygo/jazz/jazz/jaz" "make" "kernel"))

```

**Comment by jazzscheme** [comment]
Should be fixed by commits:

baa86891ebfd543d737b5a4e90c2f64a0d7e5357
Test if ##jazzstruct? is defined

7fb8d209b3a5445ac7ed3807a7a01e25d9689797
Test for customized ##gambcomp

**Comment by nodrygo** [comment]
thank's for the fix

now with fresh install I end up to
*./jam default*
*./jam: 3: ./jam: [[: not found  (WORK with bash ./jam) *
*Clonage dans './gambit'.*..
.. lot of thing and stop with last line
*(open-process '(path: "bin/jazz" arguments: ("-:daD" "-make" "all")
stdin-redirection: #f stdout-redirection: #f stderr-redirection: #f)) *

and if I try again
*./jam default*

*config*
*install*
*** ERROR IN jazz:invoke-process, "kernel/runtime/base.scm"@474.15 -- No
such file or directory
(open-process '(path: "bin/jazz" arguments: ("-run" "jam" "default")
stdin-redirection: #f stdout-redirection: #f stderr-redirection: #f))

some test with* ./jaz*  see file errlog


I wanted to test *jaz* with *jedi* for fun but sorry too complicated for
me, I will stop there

cheers


2017-08-23 15:35 GMT+02:00 Guillaume Cartier <notifications@github.com>:
