### ISSUE TITLE
Error "Invalid safety: debug" when running jam

### ISSUE THREAD

**Issue by MayamaTakeshi** [jazzscheme/jazz#9]
I got this when trying installation instructions in Ubuntu 14.04:
```
takeshi:jazz$ ./jam
./jam: 3: ./jam: [[: not found
configure
*** ERROR IN jazz:validate-configuration, "kernel/build.scm"@275.18 -- Invalid safety: debug
```

**Comment by jazzscheme** [comment]
Build command is now ./jaz

The JazzScheme website has been updated with this but is still fairly outdated so you will probably run into other problems. I plan on completely updating the website in the next few weeks.
